packages:
  - "apps/*"
  - "packages/*"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  sharp: false
  unrs-resolver: false
  electron: true

onlyBuiltDependencies:
  - electron
